[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/js/cloudinary-config.js"
  [headers.values]
    Cache-Control = "no-store"

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.svg"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
